### ISSUE TITLE
Styles are not being shown 

### ISSUE THREAD

**Issue by calbmartz** [brandon-schabel/react-component-lib-template#2]
Hello brandon-schabel, thanks in advance for the library!

When I linked the project locally, for some reason I am not able to see tailwindcss styles. I thought I was doing the link wrong but when I published the same issue still persists, did you find a way to ship tailwindcss into the components once is published? Thanks

**Comment by Vishwas-uni** [comment]
Hey @brandon-schabel ,
when i developed the library from scratch from you docs styles are not applying could you please suggest the solution.

**Comment by brandon-schabel** [comment]
@icyhookdev @Vishwas-uni https://codesandbox.io/p/sandbox/hardcore-breeze-wj3gm4?file=%2Fsrc%2Fmain.tsx%3A1%2C1

please take a look at this sample sandbox I made. I cloned the repo, and just publish the package. Then i imported it into this project https://codesandbox.io/p/sandbox/hardcore-breeze-wj3gm4?file=%2Fsrc%2Fmain.tsx%3A1%2C1 

Please note the
`import "@bschabs/react-component-library/styles.css";` in `App.tsx`

The styles aren't automatically imported. So just make sure when you publish your library you import the styles as demonstrated above

I have also updated the article here:
https://betterprogramming.pub/build-a-custom-react-component-library-with-storybook-7-beta-and-vite-4-in-2023-c52db4d733c0

If this doesn't resolve the issue please open up a new issue :) Thank you for trying this project out!

**Comment by Vishwas-uni** [comment]
Thanks for quick response @brandon-schabel it is working fine.

Don't we have any other way to achieve it just asking any inputs.
