### ISSUE TITLE
Not a module error when importing in a project

### ISSUE THREAD

**Issue by saurav-bhagat** [brandon-schabel/react-component-lib-template#3]
File '/Users/Documents/<project>/node_module/<package_name>/dist/index.d.ts' is not a module

**Comment by brandon-schabel** [comment]
@saurav-bhagat  Please provide an example project

**Comment by saurav-bhagat** [comment]
@brandon-schabel Thanks for quick response.
This got resolved just now. Missed changing the project name in `package.json` file.

Closing this Issue.

**Comment by brandon-schabel** [comment]
@saurav-bhagat Awesome glad to hear that!🚀
