### ISSUE TITLE
React hooks

### ISSUE THREAD

**Issue by otagayan-dev** [brandon-schabel/react-component-lib-template#5]
Good day sir! Thank you again for this example and the Blog. It was very helpful

I was already able to solve the _"cannot find declaration"_ by placing the `"types"` in the `"exports["."].types"`
<img width="302" alt="image" src="https://github.com/brandon-schabel/react-component-lib-template/assets/59283566/4cd9f586-9e37-4109-a62e-1ce335321d85">

**Everything works fine up until I used React Hooks**
Here is the screenshot of the error
<img width="571" alt="image" src="https://github.com/brandon-schabel/react-component-lib-template/assets/59283566/01f32274-d8cd-4d2e-8d8b-65bfe1d85e33">

Here is the  <Card/> Code Snippet
<img width="848" alt="image" src="https://github.com/brandon-schabel/react-component-lib-template/assets/59283566/1a5ff868-3c33-4993-a75b-ef89c53fb989">

Do you know where I went wrong?
I did not change anything on this repositories code.

**Comment by brandon-schabel** [comment]
@guesschronic6  hello, can you create a code sandbox with a reproduction? My guess would be you have an outdated version of react

**Comment by brandon-schabel** [comment]
@guesschronic6 Hi can you please create a codesandbox with a reproduction, otherwise I'll I'll mark it as resolved
